export default {
	STICKY_MENU_AFTER_SCROLL_POSITION: 10,
	FRONTPAGE_SLIDER_ANIMATION_TIMEOUT: 8000,
	FRONTPAGE_SLIDER_DELAY_BEFORE_ANIMATE_CAPTIONS: 100,
	FRONTPAGE_SLIDER_DELAY_OFFSET_ANIMATE_CAPTIONS: 180,
	FRONTPAGE_SLIDER_DELAY_BEFORE_NEXT: 2000,
	SCROLL_TO_TOP_OFFSET_SHOW: 150,
	SCROLL_TO_TOP_ANIMATION_TIME: 1000,
	DELAY_REMOVE_PAGE_LOADER: 1000,
	HEADER_NAV_HEIGHT: 94,
	DESKTOP_MORE_THAN: 992
};